name: forecast-modeling-demand
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - boto3=1.13.1
  - s3fs=0.4.2
  - numpy=1.18.1
  - pandas=1.2.3
  - pyarrow=0.17.0
  - pyyaml=5.3.1
  - scikit-learn=0.22.1
  - pip=20.1
  - uritools=3.0.0
  - pytest=6.2.2
  - pytest-mock=3.5.1
  - pytest-cov=2.11.1
  - flake8=3.8.4
  - pip:
    - sagemaker==1.71.0
