name: forecast-modeling-demand
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - boto3=1.13.1
  - s3fs=0.4.2
  - numpy=1.18.1
  - pandas=1.0.3
  - pyarrow=0.17.0
  - pyyaml=5.3.1
  - scikit-learn=0.22.1
  - pip=20.1
  - pip:
    - sagemaker==1.71.0