name: CI/CD
on: [pull_request]

jobs:
  miniconda:
    name: CI/CD pipeline
    runs-on: ubuntu-latest
    env:
      COVERAGE_TOTAL: 60

    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('etc/example-environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: forecast-modeling-demand
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Lint
        shell: bash -l {0}
        run: |
            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
            coverage run -m pytest -v
      - name: Report code coverage
        shell: bash -l {0}
        run: |
            coverage report -m --omit='tests/*' --fail-under=$COVERAGE_TOTAL --skip-empty
            coverage xml --omit='tests/*' --fail-under=$COVERAGE_TOTAL --skip-empty
      - name: Coverage comment in PR
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: ${{ env.COVERAGE_TOTAL }}
